name: Deploy Backend to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create deployment package
        run: |
          mkdir -p deploy
          # 必要なファイルのみコピー
          cp main.py deploy/
          cp database.py deploy/
          cp models.py deploy/
          cp requirements.txt deploy/
          
          # 不要なファイルを除外
          # .git, .github, __pycache__, .pyc, .pem ファイルは除外
      
      - name: Create .deployment file
        run: |
          echo "[config]" > deploy/.deployment
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT = false" >> deploy/.deployment
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-002-gen10-step3-1-py-oshima42'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./deploy
